package ro.noadsx15.hybrid;

import android.app.*;import android.content.Intent;import android.net.VpnService;import android.os.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.atomic.AtomicLong;

public final class DnsVpnService extends VpnService {
 public static final String START="ro.noadsx15.hybrid.START",STOP="ro.noadsx15.hybrid.STOP",STATUS="ro.noadsx15.hybrid.STATUS";public static volatile boolean running=false;public static final AtomicLong blockedCount=new AtomicLong(),allowedCount=new AtomicLong();
 private ParcelFileDescriptor tunnel;private Thread worker;private BlocklistStore rules;
 @Override public void onCreate(){super.onCreate();rules=new BlocklistStore(this);createChannel();}
 @Override public int onStartCommand(Intent intent,int flags,int startId){if(intent!=null&&STOP.equals(intent.getAction())){shutdown("Oprit");return START_NOT_STICKY;}if(running)return START_STICKY;startForeground(40,notification("Pornire…"));try{tunnel=new Builder().setSession("NoAds X15 Hybrid").setMtu(1500).addAddress("10.77.0.2",32).addRoute("10.77.0.1",32).addDnsServer("10.77.0.1").establish();if(tunnel==null)throw new IOException("Tunel indisponibil");running=true;worker=new Thread(this::loop,"NoAds-DNS");worker.start();broadcast("Activ • "+rules.size()+" domenii");return START_STICKY;}catch(Throwable e){shutdown("Eroare: "+e.getClass().getSimpleName());return START_NOT_STICKY;}}
 private void loop(){ParcelFileDescriptor p=tunnel;if(p==null)return;try(FileInputStream in=new FileInputStream(p.getFileDescriptor());FileOutputStream out=new FileOutputStream(p.getFileDescriptor())){byte[]buf=new byte[65535];while(running){int n=in.read(buf);if(n>0){byte[]reply=process(buf,n);if(reply!=null){out.write(reply);out.flush();}}}}catch(Throwable e){if(running)shutdown("Tunel oprit automat");}}
 private byte[] process(byte[]p,int n){if(n<28||(p[0]&0xF0)!=0x40)return null;int ihl=(p[0]&15)*4;if(ihl<20||n<ihl+8||(p[9]&255)!=17||u16(p,ihl+2)!=53)return null;byte[]q=Arrays.copyOfRange(p,ihl+8,n);String host=DnsPacket.host(q);if(host==null)return null;byte[]dns;if(rules.isBlocked(host)){blockedCount.incrementAndGet();dns=DnsPacket.nxdomain(q);}else{allowedCount.incrementAndGet();dns=forward(q);if(dns==null)return null;}long total=blockedCount.get()+allowedCount.get();if(total%25==0)broadcast("Blocate "+blockedCount.get()+" • Permise "+allowedCount.get());return reply(p,dns,u16(p,ihl));}
 private byte[] forward(byte[]q){for(String server:new String[]{"1.1.1.1","9.9.9.9"}){DatagramSocket s=null;try{s=new DatagramSocket();if(!protect(s))continue;s.setSoTimeout(2200);s.send(new DatagramPacket(q,q.length,InetAddress.getByName(server),53));byte[]b=new byte[4096];DatagramPacket r=new DatagramPacket(b,b.length);s.receive(r);return Arrays.copyOf(r.getData(),r.getLength());}catch(Throwable ignored){}finally{if(s!=null)s.close();}}return null;}
 private byte[] reply(byte[]req,byte[]dns,int port){int total=28+dns.length;byte[]o=new byte[total];o[0]=0x45;put16(o,2,total);o[4]=req[4];o[5]=req[5];o[8]=64;o[9]=17;System.arraycopy(req,16,o,12,4);System.arraycopy(req,12,o,16,4);put16(o,20,53);put16(o,22,port);put16(o,24,8+dns.length);put16(o,26,0);System.arraycopy(dns,0,o,28,dns.length);put16(o,10,checksum(o,0,20));return o;}
 private static int u16(byte[]b,int i){return((b[i]&255)<<8)|(b[i+1]&255);}private static void put16(byte[]b,int i,int v){b[i]=(byte)(v>>>8);b[i+1]=(byte)v;}private static int checksum(byte[]b,int o,int l){long s=0;for(int i=o;i<o+l-1;i+=2)s+=u16(b,i);if((l&1)==1)s+=(b[o+l-1]&255)<<8;while((s>>>16)!=0)s=(s&65535)+(s>>>16);return(int)(~s)&65535;}
 private void shutdown(String msg){running=false;try{if(tunnel!=null)tunnel.close();}catch(Throwable ignored){}tunnel=null;if(worker!=null)worker.interrupt();worker=null;broadcast(msg);if(Build.VERSION.SDK_INT>=24)stopForeground(STOP_FOREGROUND_REMOVE);else stopForeground(true);stopSelf();}
 @Override public void onRevoke(){shutdown("Permisiune VPN revocată");super.onRevoke();}@Override public void onDestroy(){running=false;try{if(tunnel!=null)tunnel.close();}catch(Throwable ignored){}if(worker!=null)worker.interrupt();super.onDestroy();}
 private void broadcast(String m){sendBroadcast(new Intent(STATUS).setPackage(getPackageName()).putExtra("message",m));}private void createChannel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel("noads","NoAds X15",NotificationManager.IMPORTANCE_LOW));}private Notification notification(String t){return new Notification.Builder(this,"noads").setContentTitle("NoAds X15 Hybrid").setContentText(t).setSmallIcon(android.R.drawable.ic_secure).setOngoing(true).build();}
}
